name: 'Setup Aedifex'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: wget https://github.com/LuxLang/lux/releases/download/0.6.5/aedifex_do_not_touch_3.jar && mv aedifex_do_not_touch_3.jar aedifex.jar
    - run: mv ./shell/lux.sh ./lux.sh
    - run: cd ./stdlib/ && ../lux.sh clean && cd ..

