name: test_everything
on: [push]
jobs:
  test_stdlib_on_jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup_aedifex
      - run: cd ./stdlib/ && ../lux.sh with jvm with bibliotheca test
  test_stdlib_on_node_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup_aedifex
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd ./stdlib/ && ../lux.sh with js with bibliotheca test
  test_stdlib_on_python_3:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup_aedifex
      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: cd ./stdlib/ && ../lux.sh with python with bibliotheca test
#  test_stdlib:
#    runs-on: ubuntu-latest
#    steps:
#      # Test on Lua
#      # https://github.com/marketplace/actions/setup-lua-luajit
#      - uses: xpol/setup-lua@v0.3
#      - run: cd ./stdlib/ && ../lux.sh clean && ../lux.sh with lua with bibliotheca test && cd ..
#      # Test on Ruby
#      # https://github.com/actions/setup-ruby
#      - uses: actions/setup-ruby@v1
#        with:
#          ruby-version: '2.6'
#      - run: cd ./stdlib/ && ../lux.sh clean && ../lux.sh with ruby with bibliotheca test && cd ..

