name: test_everything
on: [push]
jobs:
  test_stdlib_on_jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup_aedifex
      - run: cd ./stdlib/ && ../lux.sh with jvm with bibliotheca test
  test_aedifex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup_aedifex
      - run: cd ./stdlib/ && ../lux.sh with aedifex test
  # Temporarily disabled because of strange "replaceAll" issue on CI.
#  test_stdlib_on_node_js:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/workflows/setup_aedifex
#      # https://github.com/actions/setup-node
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '14'
#      - run: cd ./stdlib/ && ../lux.sh with js with bibliotheca test
#  test_stdlib_on_python_3:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/workflows/setup_aedifex
#      # https://github.com/actions/setup-python
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.9'
#          architecture: 'x64'
#      - run: cd ./stdlib/ && ../lux.sh with python with bibliotheca test
  # Temporarily disabled because of strange compiler bug that manifests when trying to run tests.
#  test_stdlib_on_ruby:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/workflows/setup_aedifex
#      # https://github.com/actions/setup-ruby
#      - uses: actions/setup-ruby@v1
#        with:
#          ruby-version: '2.6'
#      - run: cd ./stdlib/ && ../lux.sh with ruby with bibliotheca test
  # Temporarily disabled because the Lua version used in the CI is a bit outdated and some text/string operations fail as a consequence.
#  test_stdlib_on_lua:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/workflows/setup_aedifex
#      # https://github.com/marketplace/actions/setup-lua-luajit
#      - uses: xpol/setup-lua@v0.3
#        with:
#          lua-version: "5.3.5"
#      - run: cd ./stdlib/ && ../lux.sh with lua with bibliotheca test

